version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /apps/vscode
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /apps/idea
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
